### PR TITLE
Removing Schema self reference imports

### PR DESCRIPTION
**Pull request by ocsig**

### CODE REVIEW

**Comment by ocsig** [comment]
Only known issues cause tests to fail.

**Comment by ocsig** [comment]
Fix #558

**Comment by frots** [comment]
One of the commits in this PR broke the networks template: https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/commit/5ffb2894ea94d3545bf750a846e58de25cf0f49b#r37794922

**Pull request merged**
