### PR TITLE
chore: run all bpt tests

### PR DESCRIPTION
**Pull request by bharathkkb**
I didn't see another workflow testing unit tests in other packages, so thought I would add it to this.

### CODE REVIEW

**Review by apeabody — APPROVED** [review]

**Comment by apeabody** [comment]
Not super clear for which repo it is grabbing the commit hash.

```
TestAll/examples/vpc-example 2023-12-04T21:44:08Z command.go:185: Initialized empty Git repository in /workspace/infra/blueprint-test/examples/krm_blueprints_with_test/test/integration/.build/TestAll/examples/vpc-example/.git/
TestAll/examples/vpc-example 2023-12-04T21:44:08Z command.go:100: Running command git with args [add -A]
TestAll/examples/vpc-example 2023-12-04T21:44:08Z command.go:100: Running command git with args [commit -m "commit Mon, 04 Dec 2023 21:44:08 UTC" --author BlueprintsTest <blueprints-ci-test@google.com>]
TestAll/examples/vpc-example 2023-12-04T21:44:08Z command.go:185: [master (root-commit) 15bcf9c] "commit Mon, 04 Dec 2023 21:44:08 UTC"
TestAll/examples/vpc-example 2023-12-04T21:44:08Z command.go:185:  Author: BlueprintsTest <blueprints-ci-test@google.com>
TestAll/examples/vpc-example 2023-12-04T21:44:08Z command.go:185:  4 files changed, 142 insertions(+)
TestAll/examples/vpc-example 2023-12-04T21:44:08Z command.go:185:  create mode 100644 Kptfile
TestAll/examples/vpc-example 2023-12-04T21:44:08Z command.go:185:  create mode 100644 README.md
TestAll/examples/vpc-example 2023-12-04T21:44:08Z command.go:185:  create mode 100644 setters.yaml
TestAll/examples/vpc-example 2023-12-04T21:44:08Z command.go:185:  create mode 100644 vpc.yaml
TestAll/examples/vpc-example 2023-12-04T21:44:08Z command.go:100: Running command git with args [rev-parse HEAD]
TestAll/examples/vpc-example 2023-12-04T21:44:08Z command.go:185: 5ad3d666fd688d01a56d943f0ca4e14d05a028b1
TestAll/examples/vpc-example 2023-12-04T21:44:08Z retry.go:91: kpt [pkg update .@5ad3d666fd688d01a56d943f0ca4e14d05a028b1]
TestAll/examples/vpc-example 2023-12-04T21:44:08Z command.go:100: Running command kpt with args [pkg update .@5ad3d666fd688d01a56d943f0ca4e14d05a028b1]
TestAll/examples/vpc-example 2023-12-04T21:44:09Z command.go:185: Package "vpc-example":
TestAll/examples/vpc-example 2023-12-04T21:44:09Z command.go:185: Fetching upstream from https://github.com/GoogleCloudPlatform/blueprints@5ad3d666fd688d01a56d943f0ca4e14d05a028b1
TestAll/examples/vpc-example 2023-12-04T21:44:09Z command.go:185: fatal: remote error: upload-pack: not our ref 5ad3d666fd688d01a56d943f0ca4e14d05a028b1
TestAll/examples/vpc-example 2023-12-04T21:44:09Z command.go:185: Error: Failed to execute git command "git fetch origin --depth=1 5ad3d666fd688d01a56d943f0ca4e14d05a028b1" against repo "https://github.com/GoogleCloudPlatform/blueprints" for reference "5ad3d666fd688d01a56d943f0ca4e14d05a028b1"
TestAll/examples/vpc-example 2023-12-04T21:44:09Z command.go:185: 
TestAll/examples/vpc-example 2023-12-04T21:44:09Z command.go:185: Details:
TestAll/examples/vpc-example 2023-12-04T21:44:09Z command.go:185: fatal: remote error: upload-pack: not our ref 5ad3d666fd688d01a56d943f0ca4e14d05a028b1
TestAll/examples/vpc-example 2023-12-04T21:44:09Z command.go:185:  
```

**Comment by bharathkkb** [comment]
Thanks Andrew, I think there are a few failing tests. I will try to patch these up this week.

**Comment by bharathkkb** [comment]
@apeabody the failure turned out to be that we are trying to update a kpt pkg to a [commit on this branch](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/pull/2001/commits/5ad3d666fd688d01a56d943f0ca4e14d05a028b1). This was intended when working on the repo that owned a blueprint but in this case I don't think it ever worked. Since this is an example and limited to KRM, I decided to limit the tests to just pkg dir.

Is there an easy way to allow list a file with no-newline for the pre commit?

**Comment by apeabody** [comment]
> @apeabody the failure turned out to be that we are trying to update a kpt pkg to a [commit on this branch](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/pull/2001/commits/5ad3d666fd688d01a56d943f0ca4e14d05a028b1). This was intended when working on the repo that owned a blueprint but in this case I don't think it ever worked. Since this is an example and limited to KRM, I decided to limit the tests to just pkg dir.
> 
> Is there an easy way to allow list a file with no-newline for the pre commit?

Could add for `.json`, etc, to https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/blob/master/.pre-commit-config.yaml#L1

**Pull request merged**
