### PR TITLE
farisjarrah/cloud-sql-docs: Fixed a path error in an Cloud SQL exampl…

### PR DESCRIPTION
**Pull request by farisjarrah**
…e and added CFT commands for deployment and deleting Cloud SQL instances. Added an example template for Postgres.

Greetings,

I have been working on a CFT Cloud SQL deployment and saw a few things that could possibly use some fixing, and also a potential quality of life improvement for your users.

 1. There was an error in the README.md that had an incorrect file path. Was: `dns_managed_zone`, Changed to: `cloud_sql`
2. Incorrect file path in the README with regards to linking to the `example/cloud_sql.yaml`
3. Quality of life improvement: Added CFT commands for the deployment and deleting of the Cloud SQL instances
4. Quality of life improvement: Added an example template for Postgres.

If there are any changes you would like to see or any other fixes, please don't hesitate to let me know and I will try my best to get them patched up.

Thanks!
Faris

### CODE REVIEW

**Comment by ocsig** [comment]
Thank you for the great contribution. Would you be able to send your changes against to the cft-dm-dev branch? Otherwhise I'm holding this PR back until the end of the week when we plan to merge to master.
Also would you mind to check your examples against the schema and template in that branch?

**Comment by farisjarrah** [comment]
Sure thing, I can probably get this done by this evening.

**Comment by farisjarrah** [comment]
I've rebased off of cft-dm-dev and set that as my new upstream branch I still need to double check the schema though.

**Comment by farisjarrah** [comment]
@googlebot I consent.

**Comment by farisjarrah** [comment]
Already been merged, but I did double check the schema, thanks!

**Comment by ocsig** [comment]
I did run the schema checks before merge. Thank you for your contribution!

**Pull request merged**
