### PR TITLE
chore: Add elo into kms-solutions repo

### PR DESCRIPTION
**Pull request by romanini-ciandt**

### CODE REVIEW

**Review by erlanderlo — APPROVED** [review]
lgtm; need a backup for business continuity (and if anyone goes OOO)

**Comment by romanini-ciandt** [comment]
@bharathkkb @apeabody
Could you PTAL?

**Review by apeabody — APPROVED** [review]
validated user registration

**Comment by apeabody** [comment]
applied

**Comment by romanini-ciandt** [comment]
> applied

@apeabody thanks!!

**Pull request merged**
