### PR TITLE
feat: Ignore assets/ in int_triggers

### PR DESCRIPTION
**Pull request by NimJay**
This implements #1602.

### CODE REVIEW

**Comment by apeabody** [comment]
Would we ever want to run the INT for just images (`png`, `svg`, etc), or would it make sense to exclude those instead/as well?  If I recall, `json` is used under some /test/integration, and likely other places, so we wouldn't want to globally exclude it.

@bharathkkb @g-awmalik WDYT?

**Review by apeabody — CHANGES_REQUESTED** [review]
Thanks @NimJay!

**Comment by apeabody** [comment]
> Would we ever want to run the INT for just images (`png`, `svg`, etc), or would it make sense to exclude those instead/as well? If I recall, `json` is used under some /test/integration, and likely other places, so we wouldn't want to globally exclude it.
> 
> @bharathkkb @g-awmalik WDYT?

Per discussion let's leave as folder based for now, but add infra/assets/**

**Comment by apeabody** [comment]
Hi @NimJay - Is this PR waiting on anything?  It's still marked as draft.

**Comment by NimJay** [comment]
Hi @apeabody,
Thank you for the quick review and context (into your discussion with @bharathkkb)!

You asked:
>  Is this PR waiting on anything?

I was wondering if I need approval from either @bharathkkb or @g-awmalik
because of the [Google Doc comment thread/discussion here](https://docs.google.com/document/d/1EQjWLziWLGIMuQ1DtU3wPxhpGkrl_WVTdArOCJHr9ic/edit).
If you don't think so, feel free to merge. All looks good to me. :)

**Review by bharathkkb — APPROVED** [review]

**Review by apeabody — APPROVED** [review]

**Comment by apeabody** [comment]
applied

**Pull request merged**
