### PR TITLE
feat: add terraform-cloud-client-api

### PR DESCRIPTION
**Pull request by glasnt**
* adds terraform-cloud-client-api as a managed repo

### CODE REVIEW

**Comment by apeabody** [comment]
Hi @glasnt! Can you please add `blueprint-solutions` as admin to the repo?

**Comment by glasnt** [comment]
> Hi @glasnt! Can you please add `blueprint-solutions` as admin to the repo?

Done

**Comment by apeabody** [comment]
bots enabled

**Comment by apeabody** [comment]
applied

**Review by apeabody — APPROVED** [review]

**Pull request merged**
