### PR TITLE
Support for sourceInstanceTemplate instead of properties in Instance tmpl

### LINKED ISSUE #263: Support for sourceInstanceTemplate instead of properties in Instance template
https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/blob/32cfdff1c469761cd9b909fdd7d312111551988c/dm/templates/instance/instance.py.schema#L65

https://cloud.google.com/compute/docs/instances/create-vm-from-instance-template
https://cloud.google.com/compute/docs/reference/rest/v1/instances/insert

Example snippet:

```
    instance = {
        'name': 'myisntance',
        'type': 'gcp-types/compute-v1:instances',
        'properties':{
            'zone': 'us-central1-a',
            'project': project_id,
            'sourceInstanceTemplate': 'projects/project-123456/global/instanceTemplates/instance-template-example'
        }
    }
```

### PR DESCRIPTION
**Pull request by kopachevsky**
Added if/else block to check if sourceInstanceTemplate property exists, if true - all properties except name, project_id, zone and sourceInstanceTemplate ignored
 

Fixes #263

### CODE REVIEW

**Comment by ivankorn** [comment]
@kopachevsky why don't you squash commits ? Commit message is the same

**Comment by kopachevsky** [comment]
> @kopachevsky why don't you squash commits ? Commit message is the same

accidentally, fixed

**Comment by kopachevsky** [comment]
```
$ bats templates/instance/tests/integration/
 ✓ Creating deployment gl-akopachevskyy-dm-instance-1-nic-qkcu0b6450 from .gl-akopachevskyy-dm-instance-1-nic-qkcu0b6450.yaml
 ✓ Verifying that a Compute Instance was created in deployment gl-akopachevskyy-dm-instance-1-nic-qkcu0b6450
 ✓ Verifying that the Compute Instance was connected to the first custom network in deployment gl-akopachevskyy-dm-instance-1-nic-qkcu0b6450
 ✓ Verifying that the Compute Instance has the canIpForward property set in deployment gl-akopachevskyy-dm-instance-1-nic-qkcu0b6450
 ✓ Deleting deployment
 ✓ Creating deployment gl-akopachevskyy-dm-instance-2-nics-ldx5h37cf7 from .gl-akopachevskyy-dm-instance-2-nics-ldx5h37cf7.yaml
 ✓ Verifying that a Compute Instance was created in deployment gl-akopachevskyy-dm-instance-2-nics-ldx5h37cf7
 ✓ Verifying that the Compute Instance was connected to the first custom network in deployment gl-akopachevskyy-dm-instance-2-nics-ldx5h37cf7
 ✓ Verifying that the Compute Instance was connected to the second custom network in deployment gl-akopachevskyy-dm-instance-2-nics-ldx5h37cf7
 ✓ Verifying that the Compute Instance has the canIpForward property set in deployment gl-akopachevskyy-dm-instance-2-nics-ldx5h37cf7
 ✓ Deleting deployment
 ✓ Creating deployment gl-akopachevskyy-dm-instance-jix49ox0eo from .gl-akopachevskyy-dm-instance-jix49ox0eo.yaml
 ✓ Verifying that a Compute Instance was created in deployment gl-akopachevskyy-dm-instance-jix49ox0eo
 ✓ Verifying that the Compute Instance was connected to a custom network in deployment gl-akopachevskyy-dm-instance-jix49ox0eo
 ✓ Verifying that the Compute Instance has the canIpForward property set in deployment gl-akopachevskyy-dm-instance-jix49ox0eo
 ✓ Deleting deployment
 ✓ Creating deployment gl-akopachevskyy-dm-instance-source-template-c9o0mbzm23 from .gl-akopachevskyy-dm-instance-source-template-c9o0mbzm23.yaml
 ✓ Verifying that a Compute Instance was created in deployment gl-akopachevskyy-dm-instance-source-template-c9o0mbzm23
 ✓ Verifying that the Compute Instance was connected to a custom network in deployment gl-akopachevskyy-dm-instance-source-template-c9o0mbzm23
 ✓ Verifying that the Compute Instance has the canIpForward property set in deployment gl-akopachevskyy-dm-instance-source-template-c9o0mbzm23
   Deleting deployment  
```

**Pull request merged**
