### PR TITLE
GKE schema fixes

### PR DESCRIPTION
**Pull request by NathanHowell**
A number of properties in the GKE template have incorrect types, this fixes the ones I've run across so far.

### CODE REVIEW

**Comment by ocsig** [comment]
Hi @NathanHowell Thanks for your contribution! Github says the PR is out-of-date and it does not let me update your branch. Would you mind to do that? ( I will re-trigger the tests after.)

**Comment by NathanHowell** [comment]
@ocsig done

**Comment by sjvanrossum** [comment]
Could you please rebase your branch? :)

**Pull request merged**
