### PR TITLE
feat: allow user to specify/override outputs from the setup stage

### PR DESCRIPTION
**Pull request by muncus**
Allow user to specify/override outputs from Setup stage. This enables users to iterate quickly when running blueprint tests on an existing project.

`cft --stage verify --setup-var key=value`

These values are then accessible with `tft.GetTFSetupStringOutput("key")`, as if it had come from the setup stage. Values specified in this way take precedence over actual setup outputs.

Values are passed to the underlying `go test` command using a set of prefixed environment variables. So `--setup-var key=value` becomes `CFT_SETUP_key=value`, which is parsed in `NewTFBlueprintTest`.

This method currently works only for string values, but can be extended if desired.

### CODE REVIEW

**Comment by muncus** [comment]
chatted with @bharathkkb out of band, and he suggested some changes. i'll move this to draft until its ready again.

**Comment by muncus** [comment]
Hey folks, can i get another /gcbrun on this PR?
I've fixed the trailing whitespace, so this should be passing all the status checks.

**Comment by muncus** [comment]
Tests are green. Is there anything else needed before this PR can be merged?

If not, please merge it for me, as I do not have write permissions in this repo. Thanks!

**Comment by apeabody** [comment]
@bharathkkb - It sounds like you are familiar with the goal, would you have time to review?

**Review by bharathkkb — APPROVED** [review]
Thanks for adding this!

**Comment by muncus** [comment]
I resolved a merge conflict, so this will need another /gcbrun to get the 'cloud-foundation-cicd' tests run again. Once they pass, please merge.

**Pull request merged**
