### PR TITLE
fix(dev-tools): Ignore .jar files in lint checks

### PR DESCRIPTION
**Pull request by NimJay**
* [This Jump Start Solution GitHub repo](https://github.com/GoogleCloudPlatform/terraform-cloud-client-api/blob/main/app/java/.mvn/wrapper/maven-wrapper.jar) contains a .jar file.
* I would like the `lint` check to ignore the .jar file. This seems appropriate since all .jar files are binary files (never read by a human) not worth linting.
* Reason I committed that .jar file into the repo: it's part of the Maven wrapper. Maven (mvn) is Java's dependency management tool. The Maven wrapper ensures all developers use the same version of mvn. [This article says it's "beneficial"](https://www.baeldung.com/maven-wrapper) to have the wrapper inside source control.
* For the file changes in this PR, I took inspiration from https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/pull/1632/files.
* See related [Google-internal chat thread](https://chat.google.com/room/AAAAhNhvzPw/8ny46tkZ57k).

### CODE REVIEW

**Comment by NimJay** [comment]
* Aside: Do you know why [this commit](https://github.com/GoogleCloudPlatform/terraform-cloud-client-api/commit/e7e96a6057f98f6f1e4ba2a3d6ae3541c6ced9a2) was reverted?

**Comment by apeabody** [comment]
> * Aside: Do you know why [this commit](https://github.com/GoogleCloudPlatform/terraform-cloud-client-api/commit/e7e96a6057f98f6f1e4ba2a3d6ae3541c6ced9a2) occurred?
> * That commit overrode my initial solution to ignoring the .jar file.
> * Maybe I did something wrong when I originally set that `EXCLUDE_LINT_DIRS` variable in that lint.yaml file?

Hi @NimJay! - That file is automatically (and periodically re-) generated. As linked in the header (https://github.com/GoogleCloudPlatform/terraform-cloud-client-api/blob/main/.github/workflows/lint.yaml#L15) your custom config should be made to this `lint_env` so they are automatically included on generation: https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/blob/master/infra/terraform/test-org/org/locals.tf#L866.

Here is an example: https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/blob/master/infra/terraform/test-org/org/locals.tf#L151

That said, I agree it would be best to globally exclude jar files from the text based linters.  Thanks!

**Review by apeabody — APPROVED** [review]
Thanks for the contribution @NimJay!

@bharathkkb or @g-awmalik - any concerns?

**Review by bharathkkb — APPROVED** [review]
LGTM too

**Comment by NimJay** [comment]
@apeabody, thank so the fast response. :)

**Comment by apeabody** [comment]
Bumped the dev-tools version

**Comment by apeabody** [comment]
@NimJay - dev-tools v1.20.4 image is now avaliable

**Pull request merged**
