### PR TITLE
chore: skip favicon files in lint

### PR DESCRIPTION
**Pull request by bharathkkb**

### CODE REVIEW

**Review by apeabody — APPROVED** [review]
Repos will need to update to tools `1.12` :)

**Comment by bharathkkb** [comment]
Thanks @apeabody. Also bumped version to 1.12.3

**Review by apeabody — CHANGES_REQUESTED** [review]
I think you will want to edit here: https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/pull/1632/files#diff-f69c92f9422437f3f7e468d63c9705cd186716b563bfd080949e1dfa51cc80c2R236

**Review by apeabody — CHANGES_REQUESTED** [review]
I think you will want to edit here: https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/pull/1632/files#diff-f69c92f9422437f3f7e468d63c9705cd186716b563bfd080949e1dfa51cc80c2R236

**Comment by bharathkkb** [comment]
@apeabody added

**Review by apeabody — APPROVED** [review]

**Comment by apeabody** [comment]
@bharathkkb - Might want to add to https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/pull/1632/files#diff-f69c92f9422437f3f7e468d63c9705cd186716b563bfd080949e1dfa51cc80c2L235 as well

**Pull request merged**
