### PR TITLE
chore: add terraform-ml-image-annotation-gcf repo

### PR DESCRIPTION
**Pull request by balajismaniam**
Onboarding https://github.com/GoogleCloudPlatform/terraform-ml-image-annotation-gcf. This repo hosts UP3.1.

### CODE REVIEW

**Review by g-awmalik — APPROVED** [review]

**Comment by apeabody** [comment]
@g-awmalik - Need repo admin to apply

**Comment by bharathkkb** [comment]
@balajismaniam please grant `blueprint-solutions` admin access on the repo

**Comment by balajismaniam** [comment]
@bharathkkb @apeabody I granted admin for `blueprint-solutions`

**Comment by apeabody** [comment]
> @bharathkkb @apeabody I granted admin for `blueprint-solutions`

Thanks!

applied

**Pull request merged**
