### PR TITLE
Add subnetwork properties purpose & role

### PR DESCRIPTION
**Pull request by frots**
To allow setup of INTERNAL_HTTPS_LOADBALANCING reserved range subnet

### CODE REVIEW

**Comment by ocsig** [comment]
Something is wrong with the Cloudbuild trigger, but tested this PR manualy.
LGTM

**Comment by frots** [comment]
Thanks

**Comment by frots** [comment]
@ocsig -- when will this end up in master?

**Comment by ocsig** [comment]
Appologies, I did not realized this is not targetting Master. Can you resend it to target master? The `cft-dm-dev` is not in a shape for merging. ( After that it will be in master within hours.) If you don't have the time, I will try to find some tonight.

**Pull request merged**
