### PR TITLE
DM/CLI Not fail on cross-deployment references to existing deployments

### LINKED ISSUE #334: DM/CLI Cross deployment reference is not even trying to look up the output of the other deployments.
```
   folders: $(out.act-cft-folders.org-cft-folder.folders)
2019/09/15 00:11:46 Could not find config for deployment = cft-test-workspace-221111.act-cft-folders
```
This error is surfacing within a second, which means, this cross deployment reference is not even trying to look up the output of the other deplyoments.
I am not sure what the error means. Why is it trying to look for a config of the deployment? It should look for the output of the deployment.

### PR DESCRIPTION
**Pull request by kopachevsky**
DM/CLI Cross deployment reference was not even trying to look up the output of the other deployments.

Fixes #334

### CODE REVIEW

**Comment by ocsig** [comment]
It looks like we are running describe 2X. Can you explain why?

`
2019/09/29 21:00:28 gcloud deployment-manager deployments describe act-cft-folders --project cft-test-workspace-221111 --format yaml
2019/09/29 21:00:33 Ordered dependencies: [[cft-test-workspace-221111.acc-cft-project-dev]]
2019/09/29 21:00:33 gcloud deployment-manager manifests describe --deployment act-cft-folders --project cft-test-workspace-221111 --format yaml`

Other problem is the second describe contains `--deployment` based on the log, which is not valid. ( I guess ignored.)

**Comment by ocsig** [comment]
The following refference is still failing:
`$(out.act-cft-folders.org-cft-folder.folders)`

```
 gcloud deployment-manager manifests describe --deployment act-cft-folders --project cft-test-workspace-221111 --format yaml
    resources:
    - name: org-cft-folder
      outputs:
      - finalValue:
          org-cft-folder-fdev:
            createTime: '2019-09-29T17:30:45.613Z'
            displayName: act under Folder dev
            lifecycleState: ACTIVE
            name: folders/237656312840
            parent: folders/315320405251
          org-cft-folder-fprod:
            createTime: '2019-09-29T17:30:46.307Z'
            displayName: act under Folder prod
            lifecycleState: ACTIVE
            name: folders/894616298630
            parent: folders/315320405251
          org-cft-folder-froot:
            createTime: '2019-09-29T17:30:34.852Z'
            displayName: act under Organization
            lifecycleState: ACTIVE
            name: folders/315320405251
            parent: organizations/518838582041
        name: folders
```

**Comment by ocsig** [comment]
We had an issue with the python implementation, when the output is not a string value but a complex hashmap.

**Comment by morgante** [comment]
@kopachevsky If this is still needed, please rebase on master.

If not, please close.

**Comment by kopachevsky** [comment]
> @kopachevsky If this is still needed, please rebase on master.
> 
> If not, please close.

@morgante done, left commits unmerged commits

**Comment by kopachevsky** [comment]
@ocsig  can we merge this one?

**Pull request merged**
