### PR TITLE
add test/source.sh to set of ignored files for header checks

### PR DESCRIPTION
**Pull request by ideasculptor**

### CODE REVIEW

**Comment by ideasculptor** [comment]
@googlebot I signed it!

**Comment by morgante** [comment]
@ideasculptor FYI it doesn't look like the CLA is signed. Make sure you sign it for `ideasculptor` and `sgendler@ignw.io`.

**Comment by ideasculptor** [comment]
Where is that sgendler@ignw.io address coming from?  I don't work there any longer and it certainly isn't an address I'm using anywhere.  The fact that you are even aware of that address implies it is coming from a github configuration or something?  But I no longer have access to any ignw resources in github to undo it.  The only email address I use at github is sgendler at ideasculptor.

**Comment by morgante** [comment]
@ideasculptor It's the email address being used for your git commits, you'll have to update it to a new address: https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/setting-your-commit-email-address

**Pull request closed without merging**
