### PR TITLE
[DM] add dependsOn and fix schema

### PR DESCRIPTION
**Pull request by aaron0x**
This PR has two changes:
1. add dependsOn to bigquery_dataset and gcs_bucket
2. fix cloud_sql.py.schema. mysql also supports REGIONAL HA.

### CODE REVIEW

**Comment by ocsig** [comment]
Thank you for your contribution! Please sign the CLA and I am happy to merge your PR.

**Comment by aaron0x** [comment]
@googlebot I signed it!

**Comment by ocsig** [comment]
Tests are failing, would you be able to take a look into what can be the issue? I will do the same later this week.

**Comment by ocsig** [comment]
```
ok 1 Creating deployment cft-test-workspace-221111-bigquery-0rgi6f8k1r from .cft-test-workspace-221111-bigquery-0rgi6f8k1r.yaml
ok 2 Verifying that a dataset was created in deployment cft-test-workspace-221111-bigquery-0rgi6f8k1r
ok 3 Verifying that a table was created in the dataset in deployment cft-test-workspace-221111-bigquery-0rgi6f8k1r
not ok 4 Verifying that a table schema was created in the dataset deployment cft-test-workspace-221111-bigquery-0rgi6f8k1r
# (in test file templates/bigquery/tests/integration/bigquery.bats, line 86)
#   `[[ "$output" =~ "{\"type\":\"STRING\",\"name\":\"firstname\"}" ]]' failed
ok 5 Deleting deployment
```

```
ok 1 Creating deployment cft-test-workspace-221111-gcs-35-iam-bindings-lmkp8zjr1i from .cft-test-workspace-221111-gcs-35-iam-bindings-lmkp8zjr1i.yaml
ok 2 Verify if Storage Bucket test-bucket-lmkp8zjr1i is created 
ok 3 Verify if SAs have role roles/storage.objectViewer
not ok 4 Verify if SAs are the members of this bucket
# (in test file templates/gcs_bucket/tests/integration/gcs_35_iam_bindings.bats, line 84)
#   `run gsutil iam get "gs://${BUCKET_NAME}/" | grep serviceAccount:${TEST_SERVICE_ACCOUNT}-.*@${CLOUD_FOUNDATION_PROJECT_ID}.iam.gserviceaccount.com' failed
ok 5 Deleting deployment cft-test-workspace-221111-gcs-35-iam-bindings-lmkp8zjr1i
```

**Pull request closed without merging**
