### PR TITLE
Update the dependency on forseti config validator

### PR DESCRIPTION
**Pull request by yukinying**
This should fix https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/473.

### CODE REVIEW

**Comment by yukinying** [comment]
> @yukinying Would you mind rebasing/resolving conflicts?

Done.

**Comment by yukinying** [comment]
Is there any reason validation/forseti.go clones the logic from https://github.com/GoogleCloudPlatform/terraform-validator/blob/552d8abae972f8fd0324cf003f18261fd57657ce/tfgcv/validate_assets.go#L44?

It may possibly introduce drift between repositories.

**Comment by yukinying** [comment]
It also looks like the code is not compiling as a variable is undefined. It doesn't look like it is caused by this pull request: 

```
deployment/api_client_test.go:10:2: undefined: runGCloud
deployment/config_test.go:124:4: undefined: runGCloud
deployment/deployment_test.go:48:4: undefined: runGCloud
deployment/deployment_test.go:106:4: undefined: runGCloud
```

**Comment by morgante** [comment]
@yukinying I'm not seeing that error - `make build` works for me on both your branch and master.

**Comment by yukinying** [comment]
I checked out master and here is the result... 

```
$ cd cli

$ make test
go test ./...
go: finding github.com/terraform-providers/terraform-provider-google v2.0.0+incompatible
go: finding github.com/terraform-providers/terraform-provider-google v2.0.0+incompatible
# github.com/GoogleCloudPlatform/cloud-foundation-toolkit/cli/deployment [github.com/GoogleCloudPlatform/cloud-foundation-toolkit/cli/deployment.test]
deployment/api_client_test.go:10:2: undefined: runGCloud
deployment/config_test.go:124:4: undefined: runGCloud
deployment/deployment_test.go:48:4: undefined: runGCloud
deployment/deployment_test.go:106:4: undefined: runGCloud
?   	github.com/GoogleCloudPlatform/cloud-foundation-toolkit/cli	[no test files]
ok  	github.com/GoogleCloudPlatform/cloud-foundation-toolkit/cli/cmd	0.269s
FAIL	github.com/GoogleCloudPlatform/cloud-foundation-toolkit/cli/deployment [build failed]
?   	github.com/GoogleCloudPlatform/cloud-foundation-toolkit/cli/report	[no test files]
?   	github.com/GoogleCloudPlatform/cloud-foundation-toolkit/cli/scorecard	[no test files]
?   	github.com/GoogleCloudPlatform/cloud-foundation-toolkit/cli/validation	[no test files]
?   	github.com/GoogleCloudPlatform/cloud-foundation-toolkit/cli/validation/cai	[no test files]
?   	github.com/GoogleCloudPlatform/cloud-foundation-toolkit/cli/validation/converter	[no test files]
FAIL
make: *** [Makefile:27: test] Error 2

$ git branch -v
* master     e8e990c [ahead 30] Merge pull request #479 from katze120/scorecard-csv

$ git status
On branch master
...
```

**Comment by yukinying** [comment]
oh right, make build would work because the errors are on `*_test.go` files.

**Comment by ocsig** [comment]
> oh right, make build would work because the errors are on `*_test.go` files.

@nick4fake Please take a look at this, it looks like this PR causes some issues with your part of the DM validator.

**Comment by morgante** [comment]
@ocsig The issues aren't related to this PR at all, they were caused by @nick4fake's original validator PR.

**Pull request merged**
