### PR TITLE
fix: Version config path should look for versions.tf in current blueprint dirctory

### PR DESCRIPTION
**Pull request by q2w**
In blueprint metadata generation step, versions.tf needs to be loaded for generating version metadata. 
Currently versions.tf file is being only searched in the root directory of the blueprint. This fails to generated version metadata for the submodules.
This feature was added in https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/pull/2496

### CODE REVIEW

**Comment by q2w** [comment]
@qz267 PTAL!

**Review by qz267 — APPROVED** [review]
Thanks @q2w for the fix!

**Review by bharathkkb — APPROVED** [review]

**Comment by qz267** [comment]
@tjy9206 do we need to rerun the generate output type after ^^?

**Comment by tjy9206** [comment]
> @tjy9206 do we need to rerun the generate output type after ^^?

I don't think so since the generated output types should have nothing to do with the version, but we should double check to confirm. Will try generating again when I get a chance to setup the overheads.

**Pull request merged**
