### PR TITLE
chore: Onboard WAAP blueprint

### PR DESCRIPTION
**Pull request by gtsorbo**
Onboard WAAP blueprint to CI: https://github.com/GoogleCloudPlatform/terraform-google-waap

### CODE REVIEW

**Comment by apeabody** [comment]
We might want to hold till after #1331

**Comment by apeabody** [comment]
Hi @gtsorbo!  Could you please rebase with the new configuration format (https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/blob/master/infra/terraform/test-org/org/locals.tf#L38).  Then tag me and I'll get it merged/applied.  Cheers!

**Comment by gtsorbo** [comment]
@apeabody should be all set now!

**Review by apeabody — APPROVED** [review]
Thanks @gtsorbo!

**Comment by apeabody** [comment]
@gtsorbo - everything is applied.  Cheers!

**Pull request merged**
